### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joonkyu**

### CODE REVIEW

**Comment by CanadaHonk** [comment]
There are several issues:
- Don't use emoji for platform names
- You're skipping to step 4
- Don't change unneeded things
- Troubleshooting section is unneeded

The whole install guide would probably be better in the wiki than in the readme to allow it to be more detailed.

**Comment by joonkyu** [comment]
Take a look at it now.

**Comment by CanadaHonk** [comment]
Still changes unneeded things

**Comment by joonkyu** [comment]
Can you point out where? And I think my pull request can be edited as well by you if needed.

**Pull request closed without merging**
