### PR TITLE
Add build.sh

### PR DESCRIPTION
**Pull request by lockness-Ko**
There are no docs for building the app.asar yourself, I'm making this file for people who want to. (Just copied from the github action)

I'll also try update the wiki if I can.

### CODE REVIEW

**Comment by CanadaHonk** [comment]
I think this would be better as docs somewhere (in the GitHub wiki maybe?) than a script in the root dir? Then it could be more cross-platform/universal as well, likely.

**Comment by lockness-Ko** [comment]
> I think this would be better as docs somewhere (in the GitHub wiki maybe?) than a script in the root dir? Then it could be more cross-platform/universal as well, likely.

Yeah no worries mate, Would it be ok to make a build/ folder and put cross platform scripts in there? I could also make a dockerfile for building it too.

**Comment by txtsd** [comment]
I think just a BUILD.md with these instructions will be suitable.

**Comment by lockness-Ko** [comment]
Not sure about instructions for building for windows and mac os. I'll get to testing the Debian/Ubuntu apt install later today.

**Comment by ImperatorStorm** [comment]
Arch Linux [packages `asar`](https://archlinux.org/packages/community/any/asar/), bypassing the need to use `npm`.

**Comment by CanadaHonk** [comment]
Closing due to inactivity for now, also as build process will soon be merging with polyn't merge.

**Pull request closed without merging**
