### PR TITLE
Add ability to inject JS into main window

### PR DESCRIPTION
**Pull request by yellowsink**
This allows us to load a Javascript file from a URL and inject it into the Discord main window at load.

While not required for the use of this specifically, a common use case of loading a client mod would
most likely take advantage of the removal of content-security-policy headers, so this PR also adds this as an option.

Here is an example settings.json:
```json
{
  "openasar": {
    "jsInject": "https://github.com/GooseMod/GooseMod/releases/download/dev/index.js",
    "removeCSP": true
  }
}
```

### CODE REVIEW

**Comment by CanadaHonk** [comment]
I like the idea but unsure on whether to have basically self-XSS easily by just a url in settings.json. Also GM would not be feasible via this method as it would only using localStorage which is buggy. Looking into.

**Comment by yellowsink** [comment]
Actually yeah, I'll see if I can get re-injecting on reload working, and amend it into this PR.

**Comment by yellowsink** [comment]
oh okay, ill do some testing

**Comment by yellowsink** [comment]
OK so some fun findings but TL;DR, because of where I put it in the code, it actually does inject on reloads anyway :facepalm: cause its already inside one big dom-ready

**Comment by yellowsink** [comment]
Any advances on this?

**Comment by CanadaHonk** [comment]
Sorry :( I will likely add soon-ish once "1.0" is "done"

**Comment by yellowsink** [comment]
ooh, nice!

**Comment by yellowsink** [comment]
fixed up conflicts and rebased so merge is all clear :p
image

**Comment by yellowsink** [comment]
Sorry for all the force pushes :p but I prefer fast-forward rebasing to merge commits for keeping PRs up-to-date like this.

**Comment by Cr3atable** [comment]
> I like the idea but unsure on whether to have basically self-XSS easily by just a url in settings.json. Also GM would not be feasible via this method as it would only using localStorage which is buggy. Looking into.

Really late but I will say that the update endpoint in settings.json is very much comparable to a self-XSS, even moreso arbitrary code execution. I get that it's not the *same* thing, but there's already a way to run malicious code by putting a URL in settings.json built into Discord.

**Comment by CanadaHonk** [comment]
For performance (not having to fetch each time) I'll likely make it so you provide a string of JS code instead of a URL to download from. You could still use fetch to download code in the string anyway.

**Comment by yellowsink** [comment]
That sounds good to me

**Comment by yellowsink** [comment]
So to load from URL, one can just `fetch('url').then(r => r.text()).then(eval)`

**Comment by yellowsink** [comment]
A thought i had a couple days ago, since this just injects js now, itd go great with HLCC :p

**Comment by CanadaHonk** [comment]
I think having one "inject" key with js code is optional. Just disable CSP if being used, there isn't really a use case for injection with intact CSP.

**Comment by yellowsink** [comment]
So `removeCSP` would essentially become a `jsInject !== undefined`? I'm down for that better UX and likely what everyone wants.

**Comment by yellowsink** [comment]
Closed in c3d6ece

**Comment by yellowsink** [comment]
For future readers' reference: jsinject key is just called `js`

**Comment by yellowsink** [comment]
yep this ^

**Comment by CanadaHonk** [comment]
See reference above for explanation of commit rather than PR merge

**Pull request closed without merging**
